#!/bin/bash

# save command line arguments
script_id=$1
script_description=$2
products_dir=${REPRO_DEMO_OUT_DIRNAME}

mkdir -p ${products_dir}

if [[ -n REPRO_DEMO_TMP_DIRNAME ]] ; then
    tmp_dir=${REPRO_DEMO_TMP_DIRNAME}
    mkdir -p ${tmp_dir}
else
    tmp_dir=$(mktemp --tmpdir=/tmp -d bash_dev_XXXXXXX)
fi

# define name of result file
script_file=${tmp_dir}/${script_id}.sh
dot_file=${products_dir}/${script_id}.gv
png_file=${products_dir}/${script_id}.png

# copy query from stdin to the query file
echo "# ${script_description}" > ${script_file}
IFS=''; while read line
do
    echo "$line" >> ${script_file}
done

# execute the script on the given data file and save results as dot file
bash ${script_file} > ${dot_file}

# use graphviz to create the visualization
dot -Tpng ${dot_file} -o ${png_file}

# print the script results
echo
echo "********************************************** CELL ${script_id} ************************************************"
echo
cat ${script_file}
echo "------------------------------------------- ${script_id} OUTPUTS ------------------------------------------------"
echo
cat ${dot_file}
echo
