#!/bin/bash

# save command line arguments
cell_id=$1
cell_description=$2
products_dir=${REPRO_DEMO_OUT_DIRNAME}

mkdir -p ${products_dir}

if [[ -n REPRO_DEMO_TMP_DIRNAME ]] ; then
    tmp_dir=${REPRO_DEMO_TMP_DIRNAME}
    mkdir -p ${tmp_dir}
else
    tmp_dir=$(mktemp --tmpdir=/tmp -d bash_dev_XXXXXXX)
fi

# define name of result file
cell_code=${tmp_dir}/${cell_id}.sh
cell_output=${tmp_dir}/${cell_id}.txt
png_file=${products_dir}/${cell_id}.png

# copy stdin to the cell code file
cat /dev/null > ${cell_code}
IFS=''; while read line
do
    echo "$line" >> ${cell_code}
done

# execute the script on the given data file and save results as dot file
bash ${cell_code} > ${cell_output}

# use graphviz to create the visualization
dot -Tpng ${cell_output} -o ${png_file}

# print the script results
echo "=========================================== BASH CELL ${cell_id} =============================================="
cat ${cell_code}
echo "--------------------------------------------- OUTPUTS -------------------------------------------------"
cat ${cell_output}
echo "======================================================================================================="
echo

